#source 'https://github.com/roxiemobile/static-cocoa-frameworks.ios.git'

platform :ios, '9.0'
use_frameworks!

workspace '../RoxieMobile.NetworkingApi/NetworkingApi.xcworkspace'

def pod_from(name, *args)
  name = name.split('/').tap { |arr| arr[0] = "#{arr[0]}-SCF42" }.reject(&:empty?).join('/')
  pod(name, *args)
end

def inject_shared_dependencies_1
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'SwiftCommonsAbstractions', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'SwiftCommonsConcurrent', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'SwiftCommonsData', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'SwiftCommonsExtensions', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'SwiftCommonsLang', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
  pod 'Dispatch', :git => 'https://github.com/MamuninaNV/Dispatch.git', :branch => 'hotfix/2.0.4-patch.1'
  pod 'CryptoSwift', '~> 1.0.0'
end

def inject_shared_dependencies_2
  pod 'Alamofire', :git => 'https://github.com/MamuninaNV/Alamofire.git', :branch => 'feature/RMCMT-108'
end


target 'NetworkingApi.Converters' do
  project '../RoxieMobile.NetworkingApi/Sources/Converters/NetworkingApi.Converters.xcodeproj'

  # Dependencies
  inject_shared_dependencies_1
end


target 'NetworkingApi.Helpers' do
  project '../RoxieMobile.NetworkingApi/Sources/Helpers/NetworkingApi.Helpers.xcodeproj'

  # Dependencies
  inject_shared_dependencies_2
  pod 'SwiftCommonsLogging', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
end


target 'NetworkingApi.Http' do
  project '../RoxieMobile.NetworkingApi/Sources/Http/NetworkingApi.Http.xcodeproj'

  # Dependencies
  pod 'SwiftCommonsDiagnostics', :git => 'https://github.com/MamuninaNV/swift-commons.ios.git', :branch => 'feature/RMCMT-102'
end


target 'NetworkingApi.Rest' do
  project '../RoxieMobile.NetworkingApi/Sources/Rest/NetworkingApi.Rest.xcodeproj'

  # Dependencies
  inject_shared_dependencies_1
  inject_shared_dependencies_2
end


target 'NetworkingApi.ObjC' do
  project '../RoxieMobile.NetworkingApi/Sources/ObjC/NetworkingApi.ObjC.xcodeproj'

  # Dependencies
  inject_shared_dependencies_2
end
